# Generated by Django 5.1 on 2025-03-19 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_alter_clients_contact_alter_clients_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='contact',
            field=models.CharField(default='0000000000', max_length=15),
        ),
        migrations.AlterField(
            model_name='clients',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
